services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: master
    dockerfilePath: ./docker/images/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: administrador
      - key: N8N_BASIC_AUTH_PASSWORD
        value: administrador
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
